var _fxcmd=_fxcmd||[];
(function(){function h(b,e){e=e||window;return e.document.getElementById(b)}function z(b,e){e||(e=document.body||document.documentElement);for(var g=[],c=e.getElementsByTagName("*"),a=0;a<c.length;a++)c[a].className==b&&g.push(c[a]);return g}function p(b,e){if("undefined"===typeof e)e=document.body;else if(!e)return;return e.getElementsByTagName(b)}function u(b){var e;try{e=Array.prototype.slice.call(b)}catch(g){var c=b.length,a;e=[];for(a=0;a<c;a++)e.push(b[a])}return e}function C(b,e){var g=b.length,
c,a;for(a=0;a<g;a++)if(c=b[a])c._callType=e}function A(){var b=_fxcmd.length,e,g;for(g=0;g<b;g++)if(e=_fxcmd[g],"trackCall"===e[0]){this._wbType=e[1];this._wbChart="undefined"!==typeof e[2]?e[2]:!1;break}}function B(b,e){var g=new top.window.Image(0,0);g.onload=function(){};g.onerror=function(){};var c=b.indexOf("?"),a;a=-1<c?c===b.length-1?"":"&":"?";setTimeout(function(){g.src=b+a+e.join("&")},0)}_fxcmd.getVersion=function(){return"20140409"};var D=_fxcmd.requestUrl||"//fx.w3t.cn/fx/jsServlet3",
E=_fxcmd.chartUrl||"//fx.w3t.cn/fx/chatServlet",x=encodeURIComponent,s;s=document.addEventListener?function(b,e,g){"complete"===document.readyState&&b===window&&"load"===e?g():b.addEventListener(e,g,!1)}:function(b,e,g){"complete"===document.readyState&&b===window&&"load"===e?g():b.attachEvent("on"+e,g)};var l={getCallInfos:function(b){b instanceof Array||(b=[b]);var e={nodes:[],clk:{cls:{},ids:{}},dbclk:{cls:{},ids:{}}},g=b.length,c,a,d,f;if(b)for(f=0;f<g;f++){d=b[f].toLowerCase();a=null;c=[];switch(d){case "53kf":if(a=
h("iconDiv1"))(a=p("tr",a))&&0<a.length?c=c.concat(u(a)):c.push(h("iconDiv1"));(a=h("hz6d_53kf_invite_acc"))&&(c=c.concat([a,a.nextSibling.nextSibling]));l.addByRule("a",function(a){return-1<(a.href||"").indexOf("/chat.53kf.com/")},c);l.addByRule("img",function(a){a=a.parentNode;var b="";a&&(b=a.onclick+"");return-1<b.indexOf('window.open("http://www2.53kf.com')},c);e.clk.ids.hz6d_mnkh_talking=d;e.clk.cls.mnkf_talking=d;e.clk.cls.icon_talking=d;e.clk.cls.newChat=d;e.dbclk.cls.hz6d_kf=d;e.dbclk.cls.avatar=
d;e.dbclk.cls.mnkf_nickname=d;e.dbclk.cls.hz6d_kf=d;break;case "looyu":(a=h("doyoo_panel_main"))?c=c.concat(u(a.childNodes)):a=c.push(h("doyoo_panel"));c=c.concat([h("doyoo_mon_accept"),h("ncontent")]);0<z("group_title",h("allcontent")).length&&(c=z("group_title",h("allcontent")));l.addByRule("a",function(a){a=a.href||"";return-1<a.indexOf(".OpenKF()")||-1<a.indexOf(".looyu.com/chat")},c);l.addByRule("img",function(a){return null!==a.getAttribute("looyu_bound")},c);break;case "talk99":(a=h("doyoo_panel"))&&
(c=c.concat(u(p("a",a))));c=c.concat([h("doyoo_mon_accept")]);l.addByRule("a",function(a){a=a.href||"";return-1<a.indexOf(".OpenKF()")||-1<a.indexOf(".talk99.cn/chat")},c);l.addByRule("img",function(a){return null!==a.getAttribute("looyu_bound")},c);break;case "tq":(a=h("tq_float_m_content"))&&(c=c.concat(u(a.childNodes)));c.push(h("tq_invit_accept"));l.addByRule("a",function(a){return-1<(a.href||"").indexOf(".tq.cn/")},c);break;case "live800":l.addByRule("a",function(a){var b=a.getAttribute("onclick")||
"";a=a.href||"";b&&(b=b.toString());return-1<b.indexOf("openChat")||-1<b.indexOf("globalInviteWindow.accept")||-1<a.indexOf("openChat")||-1<a.indexOf("live800.com/live800/chatClient")},c);break;case "bdbridge":(a=h("IconGp"))&&(0<a.getElementsByTagName("div").length?l.addByRule("div",function(a){return(a=a.className)&&-1<a.indexOf("bdbridge-group-item")},c):c.push(h("bridgehead")));l.addByRule("a",function(a){return(a=a.href)&&0===a.indexOf("http://qiao.baidu.com")},c);(a=h("chatnow"))?c.push(a):
c.push(h("BDBridgeInviteWrap"));break;case "qq":(a=h("qq_kefu"))&&(c=c.concat(u(p("a",a))));l.addByRule("a",function(a){a=a.href||"";var b=["qq.com/wpa","wpa.qq.com","qq.com/webc","crm2.qq.com"],d=b.length,c;for(c=0;c<d;c++)if(-1<a.indexOf(b[c]))return!0;return!1},c);l.addByRule(["a","img","area"],function(a){(a=a.getAttribute("onclick")||"")&&(a=a.toString());return-1<a.indexOf("wpa.b.qq.com")},c);break;case "comm100":c.push(h("comm100_FloatImageButton"));break;case "swt":l.addByRule(["a","img",
"area"],function(a){(a=a.getAttribute("onclick")||"")&&(a=a.toString());return-1<a.indexOf("openZoosUrl(")},c)}C(c,d);e.nodes=e.nodes.concat(c)}return e},addByRule:function(b,e,g,c){"string"===typeof b&&(b=[b]);var a=b.length,d,f,k,m,h;for(d=0;d<a;d++)for(f=p(b[d],c),k=f.length,h=0;h<k;h++)m=f[h],e(m)&&g.push(m)}},q,v;_fxcmd._getFx?(q=_fxcmd._getFx(),v=q.constructor.prototype):(q=new A,v=A.prototype);var y=navigator.userAgent.toLowerCase(),F=-1<y.indexOf("msie 8")||-1<y.indexOf("msie 7")||-1<y.indexOf("msie 6");
q.wcLoaded=!0;if(q._wbType)if(q._wbChart){var w=function(b){var e="ctid cu wt sn sid sml stel dept comp role time cont".split(" "),g=e.length,c=b.length,a,d,f,k,m;for(k=0;k<c;k++){d=b[k];f=[];for(m=0;m<g;m++)a=e[m],f.push("fx_wc_"+a+"="+(x(d[a])||""));f.push("fxac="+_fxcmd.sid);f.push("fxdomain="+document.referrer);a=E;f=f.join("&");var h=m=d=void 0,l=void 0,n=void 0,p=void 0,h=f.length;m=0;for(d="";m<h;){l=f.charCodeAt(m++)&255;if(m==h){d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(l>>
2);d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((l&3)<<4);d+="==";break}n=f.charCodeAt(m++);if(m==h){d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(l>>2);d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((l&3)<<4|(n&240)>>4);d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((n&15)<<2);d+="=";break}p=f.charCodeAt(m++);d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(l>>
2);d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((l&3)<<4|(n&240)>>4);d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((n&15)<<2|(p&192)>>6);d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(p&63)}B(a,[d])}},r=function(b){if(!b)return"";var e,g="",c=0;e=b.nodeType;if(!e)for(;e=b[c];c++)g+=r(e);else if(1===e||9===e||11===e){if("string"===typeof b.textContent)return b.textContent;for(b=b.firstChild;b;b=b.nextSibling)g+=
r(b)}else if(3===e||4===e)return b.nodeValue;return g},t,n=0;switch(q._wbType[0]){case "looyu":t=function(){for(var b=h("chatDiv").childNodes,e=b.length,g=[],c=window.conf,a,d,f,k;n<e;n++){k=b[n];a=k.className;if(/(^|\s+)inMsg(\s+|$)/.test(a))a="0";else if(/(^|\s+)outMsg(\s+|$)/.test(a))a="1";else continue;d={ctid:c.chatId,cu:c.UId,wt:"looyu",sn:c.realName,sid:c.userName,sml:c.mail,stel:c.phone,dept:c.deptName,comp:c.compName,role:a};a=p("span",k.firstChild);f=new Date;a&&a.length?(a=a[1].innerHTML.match(/^\((.+)\)$/)[1],
a=f.getFullYear()+"/"+a.replace("-","/"),a=new Date(a),a.getHours()!==f.getHours()&&a.getFullYear()!==f.getFullYear()?a.setFullYear(f.getFullYear()-1):a.setFullYear(f.getFullYear()),d.time=a.getTime()):d.time=f.getTime();if(a=k.childNodes[1])d.cont=r(a);g.push(d)}0<g.length&&w(g)};break;case "53kf":t=function(){var b=window.top.window,e=h("box-main-l-disp",b).childNodes,g=e.length,c=[],a,d,f,k,m=h("tab_card_email",b)||"",l=h("tab_card_phone",b)||"";m&&(m=m.innerHTML);l&&(l=l.innerHTML);for(;n<g;n++){f=
e[n];a=f.className;if(/(^|\s+)recv-msg-content(\s+|$)/.test(a))a="0";else if(/(^|\s+)send-msg-content(\s+|$)/.test(a))a="1";else continue;k={ctid:b.firewall_uuid,cu:b.myid,wt:"53kf",sn:b.obj_name,sid:b.obj_id,sml:m,stel:l,dept:"",comp:b.cname,role:a};a=f.previousSibling;d=new Date;a&&a.length&&(a=a.innerHTML.split("&nbsp;")[1].split(":"),a[0]!==d.getHours()&&"23"===a[0]&&d.setDate(d.getDate()-1),d.setHours(a[0]),d.setMinutes(a[1]),d.setSeconds(a[2]));k.time=d.getTime();k.cont=r(f);c.push(k)}0<c.length&&
w(c)};break;case "live800":t=function(){for(var b=window.top.window,e=h("padding",b).childNodes,g=e.length,c=[],a,d,f,k,m;n<g;n++){k=e[n];a=k.className;if(/(^|\s+)operator(\s+|$)/.test(a))a="0";else if(/(^|\s+)visitor(\s+|$)/.test(a))a="1";else if(k.previousSibling&&k.previousSibling.getAttribute("role"))a=k.previousSibling.getAttribute("role");else continue;k.setAttribute("role",a);m={ctid:b.LIM.config.timestamp||b.LIM.config.tm,cu:b.LIM.robotConstants.vid,wt:"live800",sn:"",sid:"",sml:"",stel:"",
dept:"",comp:"",role:a};d=p("label",k);f=new Date;d&&d.length&&(d=d[0].innerHTML.match(/^\((.+)\)$/)[1].split(":"),d[0]!==f.getHours()&&"23"===d[0]&&f.setDate(f.getDate()-1),f.setHours(d[0]),f.setMinutes(d[1]),f.setSeconds(d[2]));m.time=f.getTime();"0"==a&&(m.cont=r(p("p",k)[1])||r(p("p",k)[0]));"1"==a&&(m.cont=r(p("div",k)[0]));c.push(m)}0<c.length&&w(c)};break;case "swt":t=function(){for(var b=window.top.window,e=document.body.childNodes,g=e.length,c=[],a,d,f,k;n<g;n++){k=e[n];a="";f=k.className;
if(/(^|\s+)operatorfont(\s+|$)/.test(f))d="0";else if(/(^|\s+)clientfont(\s+|$)/.test(f))d="1";else continue;(f=k.previousSibling)&&f.firstChild&&(f=f.firstChild.innerHTML.split("&nbsp;"),"0"===d&&(a=f[0]),f=f[1]);d={ctid:b.c47,cu:b.c48,wt:"swt",sn:a,sid:"",sml:"",stel:"",dept:"",comp:"",role:d};a=new Date;f&&f.length?(f=a.getFullYear()+"/"+f.replace("-","/"),f=new Date(f),f.getHours()!==a.getHours()&&f.getFullYear()!==a.getFullYear()?f.setFullYear(a.getFullYear()-1):f.setFullYear(a.getFullYear()),
d.time=f.getTime()):d.time=a.getTime();d.cont=r(k);c.push(d)}0<c.length&&w(c)}}t&&top.window.setInterval(function(){t()},1E3)}else v.bindTrans=function(){var b=this,e=l.getCallInfos(this._wbType),g=e.nodes,c=g.length,a,d;for(d=0;d<c;d++)(a=g[d])&&!a._wcbd&&(F?function(c){s(a,"click",function(){b.trackCallTrans(c._callType)})}(a):s(a,"click",function(){b.trackCallTrans(this._callType)}),a._wcbd=!0);document.body._wcbd||(s(document.body,"click",function(a){a=a.target;var c=e.clk.ids,d=e.clk.cls,g;if(a&&
!a._wcbd)if(c=c[a.id])b.trackCallTrans(c);else for(g in d)if(-1<a.className.indexOf(g)){b.trackCallTrans(d[g]);break}}),s(document.body,"dblclick",function(a){a=a.target;var c=e.dbclk.ids,d=e.dbclk.cls,g;if(a&&!a._wcbd)if(c=c[a.id])b.trackCallTrans(c);else for(g in d)if(-1<a.className.indexOf(g)){b.trackCallTrans(d[g]);break}}),document.body._wcbd=!0)},v.trackCallTrans=function(b){var e=[];b={ty:b,uid:{looyu:window.doyoo&&window.doyoo.env.uId}[b]||""};for(var g in b)b.hasOwnProperty(g)&&e.push(g+
':"'+x(b[g])+'"');this.wc={fxwc:"{"+e.join(",")+"}"};this.trackPage?(this.updateTInfo(),this.trackPage()):B(D,["fxwc="+x(this.wc.fxwc),"fxac="+_fxcmd.sid])},_fxcmd._getFx?setTimeout(function(){q.bindTrans()},500):s(window,"load",function(){q.bindTrans()})})();
